name: flutter_fast
description: flutter_fast is a versatile CLI tool designed to streamline your Flutter development workflow. It provides a range of functionalities to enhance productivity, including managing Flutter environments, generating code assets, and handling common development tasks efficiently.
version: 1.0.2
homepage: https://github.com/pavans-open-source/flutter_fast_cli.git
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  dcli: ^6.0.5
  args: ^2.5.0

executables:
  flutter_fast: flutter_fast.dart
